version: '3.8'
services:
  maxvehicle-postgresql:
    image: postgres:13.2
    volumes:
      - ~/volumes/jhipster/maxVehicle/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=yourStrong(!)Password
      - POSTGRES_DB=maxvehicle
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
